image: continuumio/miniconda3:latest

variables:
  EXTERNAL_GIT_DIR: "/external-git"

test:
  script:
    - mkdir $EXTERNAL_GIT_DIR
    - CI_DIR=$PWD
    - cd $EXTERNAL_GIT_DIR; export RUN_PRIVATE_TESTS=yes && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/CCA-Physics/monorepo.git || export RUN_PRIVATE_TESTS=no; cd $CI_DIR
    - bash ./scripts/gitlab-ci/01-create-env.sh
    - if [ "$RUN_PRIVATE_TESTS" = yes ]; then bash ./scripts/gitlab-ci/02-install-private.sh; fi
    - bash ./scripts/gitlab-ci/03-test.sh
