cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - $HOME/miniconda
    - $HOME/.cache/pip

variables:
  PYTHON: "3.7"
  MINICONDA_DIR: "$HOME/miniconda"
  EXTERNAL_GIT_DIR: "$HOME/external-git"

stages:
  - install
  - test

install:


install:
  stage: install
  script:
    - bash ./scripts/gitlab-ci/00-install-miniconda.sh
    - bash ./scripts/gitlab-ci/01-create-env.sh
    - bash ./scripts/gitlab-ci/02-install-pymedphys.sh
    - bash ./scripts/gitlab-ci/03-install-private.sh

test:
  stage: test
  script: bash ./scripts/gitlab-ci/10-test.sh
