image: registry.gitlab.com/pymedphys/pymedphys/ci:latest  # continuumio/miniconda3:latest

variables:
  EXTERNAL_GIT_DIR: "/external-git"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

test:
  script:
    - mkdir $EXTERNAL_GIT_DIR
    - CI_DIR=$PWD

    # Attempt to download the private repo `monorepo`. If access is not
    # available set an env variable `RUN_PRIVATE_TESTS=no`
    - cd $EXTERNAL_GIT_DIR; export RUN_PRIVATE_TESTS=yes && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/CCA-Physics/monorepo.git || export RUN_PRIVATE_TESTS=no; cd $CI_DIR
    - bash ./scripts/gitlab-ci/01-install-pymedphys.sh
    - bash ./scripts/gitlab-ci/02-check-nbstripout.sh

    # Only install private packages if `RUN_PRIVATE_TESTS` is set to yes
    - if [ "$RUN_PRIVATE_TESTS" = yes ]; then bash ./scripts/gitlab-ci/03-install-private.sh; fi
    - bash ./scripts/gitlab-ci/04-test.sh

ci-docker-build:
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/pymedphys/pymedphys/ci ./scripts/gitlab-ci
    - docker push registry.gitlab.com/pymedphys/pymedphys/ci
  only:
    - master
