image: continuumio/miniconda3:latest

variables:
  EXTERNAL_GIT_DIR: "/external-git"

test:
  script:
    - bash ./scripts/gitlab-ci/00-create-env.sh
    - bash ./scripts/gitlab-ci/01-install-private.sh
    - bash ./scripts/gitlab-ci/02-test.sh
