cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - $HOME/miniconda
    - $HOME/.cache/pip

variables:
  PYTHON: "3.7"
  MINICONDA_DIR: "$HOME/miniconda"

stages:
  - install
  - test

install:
  stage: install
  script: bash ./scripts/gitlab-ci/install.sh

test:
  stage: test
  script: bash ./scripts/gitlab-ci/test.sh
