jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: CondaEnvironment@1
        inputs:
          createOptions: --file ./environment.yml
      - task: Bash@3
        displayName: 'install-pymedphys'
        inputs:
          targetType: 'filePath'
          filePath: ./scripts/azure-pipelines/01-install-pymedphys.sh
      - task: Bash@3
        displayName: 'check-nbstripout'
        inputs:
          targetType: 'filePath'
          filePath: ./scripts/azure-pipelines/02-check-nbstripout.sh
      - task: Bash@3
        displayName: 'test'
        inputs:
          targetType: 'filePath'
          filePath: ./scripts/azure-pipelines/03-test.sh
