jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: echo '/home/vsts/.conda/bin' | cat - /etc/environment > temp && mv temp /etc/environment
        displayName: 'Add Conda bin to PATH'
      - template: ./scripts/azure-pipelines/template.yml

  - job: 'Windows'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: ./scripts/azure-pipelines/template.yml

  - job: 'macOS'
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - bash: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew install findutils && echo '/usr/local/opt/findutils/libexec/gnubin' | cat - /etc/paths > temp && mv temp /etc/paths
        displayName: 'Install GNU xargs'
      - template: ./scripts/azure-pipelines/template.yml
