jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: ./scripts/azure-pipelines/template.yml

  - job: 'Windows'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: ./scripts/azure-pipelines/template.yml

  - job: 'macOS'
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - bash: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew install findutils
        displayName: 'install GNU xargs'
      - template: ./scripts/azure-pipelines/template.yml
