[build]
  command = "python ./scripts/netlify.py"
  publish = "site"


[[redirects]]
  from = "/en/stable/*"
  to = "/:splat" 301!

[[redirects]]
  from = "/en/latest/*"
  to = "/:splat" 301!

[[redirects]]
  from = "/en/0.8.x/*"
  to = "/:splat" 301!

[[redirects]]
  from = "/en/0.7.x/*"
  to = "/:splat" 301!

[[redirects]]
  from = "/en/0.6.x/*"
  to = "/:splat" 301!

[[redirects]]
  from = "/en/0.5.x/*"
  to = "/:splat" 301!

[[redirects]]
  from = "https://pymedphys.netlify.com/*"
  to = "https://pymedphys.com/:splat" 301!

[[redirects]]
  from = "https://pymedphys.com/*"
  to = "https://docs.pymedphys.com/:splat" 307!

[[redirects]]
  from = "/*"
  to = "/index.html" 200
