steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: pymedphys
      packageSpecs: python=3 pymedphys nbstripout pylint coverage mypy pytest xarray Pillow pip
      updateConda: true
      createOptions: --channel conda-forge
  - bash: source activate pymedphys && pip install -e .
    displayName: 'Install development version of PyMedPhys'
  - bash: source activate pymedphys && echo `which xargs` && find . -iname \*.ipynb | xargs -d "\n" nbstripout && git add -A && git diff HEAD --name-only --exit-code -- '*ipynb'
    displayName: 'Check that notebooks have no included output'
  - bash: source activate pymedphys && python setup.py test
    displayName: 'Run the full pytest suite'
