steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3 latest
    inputs:
      versionSpec: '3'
  - task: CondaEnvironment@1
    inputs:
      packageSpecs: pymedphys nbstripout pylint coverage mypy pytest xarray Pillow
      installOptions: --channel conda-forge
  - bash: pip install -e .
    displayName: 'install-pymedphys'
  - bash: find . -iname \*.ipynb | xargs -d "\n" nbstripout && git add -A && git diff HEAD --name-only --exit-code -- '*ipynb'
    displayName: 'check-nbstripout'
  - bash: python setup.py test
    displayName: 'test'
